os:
  - linux

language: python
python:
  - 3.7

matrix:
  include:
    - os: linux
      name: Python
      install: ""
      script:
        - sudo apt-get install xvfb python-tk
        - sudo exec Xvfb :8 -screen 0 640x480x24 2>/tmp/Xvfb.log &
        

script: python install_tkdnd.py
      
