matrix:
  include:
    - os: linux
      name: Python
      python:
        - 3.7
      install: ""
      script:
        - sudo apt-get install xvfb python-tk
        - sudo exec Xvfb :8 -screen 0 640x480x24 2>/tmp/Xvfb.log &
        - sudo python install_tkdnd.py
      
