jobs:
  include:
    - name: "Python 3.7 on Ubuntu Bionic"
      language: shell
      dist: bionic
      before_install:
        - sudo apt-get install -qq xvfb python3-tk
        - exec Xvfb :8 -screen 0 640x480x24 2>/tmp/Xvfb.log &
      script: "DISPLAY=:8 sudo python3 install_tkdnd.py"
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode11  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      # python: 3.7         # 'python:' is ignored on Travis CI macOS
      before_install: 
        - python3 --version ; pip3 --version ; sw_vers
      script: "sudo sudo sh -c 'python3 install_tkdnd.py' "
    - name: "Python 3.7.6 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      # python: 3.7         # 'python:' is ignored on Travis CI Windows
      before_install:
        - choco install python --version=3.7.6.20200110
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      script: python install_tkdnd.py
notifications:
  email: false
